const activities = [
  { id: 1, title: "Dumpling Stories", theme: "cooking", meta: "60 min · 2–6 people", desc: "Make a family recipe together and record the story behind it.", tag: "Hands-on", brief: "Agents, craft 1 dumpling in 60 minutes. Precision mandatory. Failure if judged ‘Can be better.’", quote: "Tomorrow becomes today when the mission is only 60 minutes.", agentProfile: { name: "Agent Akan Datang", emoji: "⌛", quote: "I keep postponing family time, but this mission gives us a place to begin." } },
  { id: 2, title: "Neighbourhood Memory Walk", theme: "heritage", meta: "45 min · Gentle pace", desc: "Follow a short route and swap memories about places that shaped you.", tag: "Low mobility", brief: "Agents, follow one familiar route and collect three memories. The mission succeeds when every voice gets room.", quote: "The places we know can open conversations we did not expect.", agentProfile: { name: "Agent Zip Lip", emoji: "🤐", quote: "A walk gives us something to talk about when words feel difficult." } },
  { id: 3, title: "Build & Race", theme: "arts", meta: "60 min · 2–5 people", desc: "Build a model vehicle, then let friendly competition do the talking.", tag: "Creative", brief: "Agents, assemble and deploy your vehicle. Race to survive. Failure if immobilized.", quote: "Build together first. Talk naturally after.", agentProfile: { name: "Agent Ice", emoji: "🧊", quote: "Working side by side can warm up a connection that feels distant." } },
  { id: 4, title: "Family Photo Lab", theme: "arts", meta: "15 min · Indoors", desc: "Take five photos that show what home feels like to each person.", tag: "Quick connect", brief: "Agents, take five photographs that show what home feels like. Share one story for each image.", quote: "Start small. Move before the awkwardness catches you.", agentProfile: { name: "Agent Zip Lip", emoji: "🤐", quote: "The camera gives us a gentle way to start the conversation." } },
  { id: 5, title: "Warm Feet, Warm Hearts", theme: "volunteering", meta: "30 min · Flexible", desc: "Prepare a small care package for someone in your community.", tag: "Care-led", brief: "Agents, complete a warm care mission with patience and respect. Gentle actions count.", quote: "Care can say what words cannot.", agentProfile: { name: "Agent Akan Datang", emoji: "⌛", quote: "A small act of care can move from tomorrow into today." } },
  { id: 6, title: "Letters Across Time", theme: "heritage", meta: "30 min · Quiet activity", desc: "Write a short letter to a family member, past or present.", tag: "Conversation", brief: "Agents, write a short message of love or appreciation. The mission fails only if the words remain unsent.", quote: "Words are easier when the mission gives them a shape.", agentProfile: { name: "Agent Ice", emoji: "🧊", quote: "A letter can hold the warmth that is hard to say aloud." } }
];
// Edit each activity's visual card details here without changing the renderer.
const activityPresentation = {
  1: { operation: "Deep Dive", fit: 96, spaces: 64, tags: ["60 min", "Hands-on", "Heritage"], image: "https://media.base44.com/images/public/6a26606da56b24dec75ea012/2ae1847a0_Screenshot2026-06-10132457.png" },
  2: { operation: "Lite Moments", fit: 88, spaces: 64, tags: ["45 min", "Gentle", "Low prep"], image: "https://media.base44.com/images/public/6a26606da56b24dec75ea012/08901186c_image.png" },
  3: { operation: "Deep Dive", fit: 90, spaces: 64, tags: ["60 min", "Creative", "Challenge"], image: "https://media.base44.com/images/public/6a26606da56b24dec75ea012/30bd7a419_Screenshot2026-06-10132527.png" },
  4: { operation: "Lite Moments", fit: 88, spaces: 64, tags: ["15 min", "Me + 1", "Low prep"], image: "/images/FamilyPhoto.png" },
  5: { operation: "Lite Moments", fit: 82, spaces: 64, tags: ["15 min", "Care", "Family"], image: "https://media.base44.com/images/public/6a26606da56b24dec75ea012/b2fc4bf10_image.png" },
  6: { operation: "Deep Dive", fit: 78, spaces: 64, tags: ["30 min", "Memories", "Heartfelt"], image: "/images/massage.png" }
};
activities.forEach(activity => Object.assign(activity, activityPresentation[activity.id]));
const themeNames = { cooking: "Cooking", heritage: "Heritage trails", arts: "Arts & making", volunteering: "Family volunteering" };
const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
const esc = value => String(value ?? "").replace(/[&<>\"]/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;" }[char]));
let activeTheme = "all";
let votes = JSON.parse(localStorage.getItem("cb_votes") || "{}");
let ideas = JSON.parse(localStorage.getItem("cb_ideas") || "null") || [
  { title: "Gentle senior kickboxing", description: "A friendly, seated or standing movement session.", votes: 14 },
  { title: "Teach me your favourite song", description: "Families share one song and the memory attached to it.", votes: 9 },
  { title: "Intergenerational garden day", description: "Plant something together and return to see it grow.", votes: 6 }
];
function toast(message) { const element = $("#toast"); element.textContent = message; element.classList.add("show"); clearTimeout(toast.timer); toast.timer = setTimeout(() => element.classList.remove("show"), 3200); }
function renderActivities() { const query = $("#activitySearch").value.trim().toLowerCase(); const list = activities.filter(activity => (activeTheme === "all" || activity.theme === activeTheme) && `${activity.title} ${activity.desc} ${activity.tag}`.toLowerCase().includes(query)); $("#activityGrid").innerHTML = list.map(activity => `<article class="activity-card"><div class="activity-image theme-${activity.theme}" style="${activity.image ? `background-image:url('${esc(activity.image)}')` : ""}"><span>${activity.theme === "cooking" ? "✦" : activity.theme === "heritage" ? "◌" : activity.theme === "arts" ? "△" : "+"}</span><b>${themeNames[activity.theme]}</b>${activity.fit >= 85 ? `<strong class="top-fit">Top fit</strong>` : ""}</div><div class="activity-body"><span class="card-label">${esc(activity.operation)}</span><h3>${esc(activity.title)}</h3><div class="fit-meter"><div><b>${activity.fit}%</b><span>Activity fit</span></div><i style="width:${activity.fit}%"></i></div><div class="activity-stats"><span><b>${esc(activity.meta.split("·")[0].trim())}</b><small>Time</small></span><span><b>2–8</b><small>Pax</small></span><span><b>${activity.fit}%</b><small>Fit</small></span></div><div class="availability-row"><span>Availability</span><b>${activity.spaces} spaces</b></div><div class="availability-track"><i style="width:${Math.min(100, activity.spaces / 64 * 100)}%"></i></div><div class="activity-agent"><span>${activity.agentProfile?.emoji || "✦"}</span><div><b>${esc(activity.agentProfile?.name || "Captain Bond")}</b><p>“${esc(activity.agentProfile?.quote || activity.quote)}”</p></div></div><div class="activity-tags">${(activity.tags || [activity.tag]).map(tag => `<span>${esc(tag)}</span>`).join("")}</div><button class="button primary full-button" data-register="${activity.id}">View activity brief <span>→</span></button></div></article>`).join(""); $("#directoryEmpty").classList.toggle("hidden", !list.length); }
function renderIdeas() { const total = ideas.reduce((sum, idea) => sum + idea.votes, 0); $("#ideaList").innerHTML = ideas.map((idea, index) => `<article class="idea-row"><button class="vote-button ${votes[index] ? "voted" : ""}" data-vote="${index}" aria-label="Upvote ${esc(idea.title)}"><b>${idea.votes}</b><small>votes</small><span>↑</span></button><div><h4>${esc(idea.title)}</h4><p>${esc(idea.description || "Community proposal")}</p></div></article>`).join(""); $("#thresholdProgress").style.width = `${Math.min(100, total / 20 * 100)}%`; }
function chatMessage(text, from = "bot") { const message = document.createElement("div"); message.className = `chat-message ${from}`; message.textContent = text; $("#chatMessages").append(message); $("#chatMessages").scrollTop = $("#chatMessages").scrollHeight; }
function answer(question) { const query = question.toLowerCase(); if (query.includes("safeguard") || query.includes("unsafe") || query.includes("support")) return "You can contact our trained support team from Safeguarding Support. For immediate danger, contact local emergency services."; if (query.includes("register")) return "Choose an activity and use its registration option. Assisted Registration is available in the header if you would prefer a person to help."; if (query.includes("recommend") || query.includes("activity")) return "For a low-pressure start, try Family Photo Lab. For a longer shared task, Dumpling Stories is a popular choice."; return "I can help with activity recommendations, registration, accessibility questions, and safeguarding support."; }
function go(selector) { $(selector)?.scrollIntoView({ behavior: "smooth", block: "start" }); }
window.addEventListener("load", () => setTimeout(() => $("#loadingScreen").classList.add("hide"), 700));
$("#menuToggle").addEventListener("click", () => { const nav = $("#mainNav"); const open = nav.classList.toggle("open"); $("#menuToggle").setAttribute("aria-expanded", open); });
$$('#mainNav a').forEach(link => link.addEventListener("click", () => $("#mainNav").classList.remove("open")));
$("#assistButton").addEventListener("click", () => toast("Assisted Registration: call +65 6123 4567 or email support@captainbond.example"));
$("#activitySearch").addEventListener("input", renderActivities);
$("#themeFilter").addEventListener("change", event => { activeTheme = event.target.value; $$("#directoryTags button").forEach(button => button.classList.toggle("active", button.dataset.theme === activeTheme)); renderActivities(); });
$$("#directoryTags button").forEach(button => button.addEventListener("click", () => { activeTheme = button.dataset.theme; $("#themeFilter").value = activeTheme; $$("#directoryTags button").forEach(item => item.classList.toggle("active", item === button)); renderActivities(); }));
function openActivityBrief(activity) {
  const selectedAgent = activity.agentProfile?.name || "Choose an agent profile";
  const selectedEmoji = activity.agentProfile?.emoji || "✦";
  const agentQuote = activity.agentProfile?.quote || activity.quote;
  $("#activityModalContent").innerHTML = `<div class="activity-modal-head"><div><span class="eyebrow">${esc(activity.meta.split("·")[0].trim())}</span><h2 id="activityModalTitle">${esc(activity.title)}</h2></div><button class="modal-close" type="button" aria-label="Close activity brief" data-close-activity>×</button></div><div class="activity-modal-main"><div class="modal-activity-art theme-${activity.theme}"><span>${activity.theme === "cooking" ? "✦" : activity.theme === "heritage" ? "◌" : activity.theme === "arts" ? "△" : "+"}</span><b>${esc(themeNames[activity.theme])}</b></div><div class="mission-brief-box"><span class="eyebrow">Mission brief</span><p>${esc(activity.brief)}</p></div><div class="mission-agent-box"><span class="mission-agent-icon">${selectedEmoji}</span><div><b>${esc(selectedAgent)}</b><p>“${esc(agentQuote)}”</p></div></div><button class="button primary accept-mission" type="button" data-accept-activity="${activity.id}">Accept mission <span>→</span></button></div>`;
  $("#activityModal").classList.remove("hidden");
  document.body.classList.add("modal-open");
}
function closeActivityModal() { $("#activityModal").classList.add("hidden"); document.body.classList.remove("modal-open"); }
function openRegistration(activity) {
  $("#activityModalContent").innerHTML = `<div class="activity-modal-head"><div><span class="eyebrow">${esc(activity.meta.split("·")[0].trim())}</span><h2>Mission Registration</h2><p>Fill in your details to reserve your mission slot.</p></div><button class="modal-close" type="button" aria-label="Close registration" data-close-activity>×</button></div><div class="activity-modal-main registration-main"><div class="registration-steps"><i></i><i></i><i></i></div><label class="modal-label">Number of people attending</label><div class="pax-controls"><button type="button" data-pax="-1">−</button><b id="modalPax">1</b><button type="button" data-pax="1">+</button></div><label class="modal-label">Preferred time slot</label><div class="modal-times">${["1:00 PM", "2:00 PM", "3:00 PM", "4:00 PM", "5:00 PM", "6:00 PM", "7:00 PM", "8:00 PM"].map(time => `<button type="button">${time}<small>8 left</small></button>`).join("")}</div><label class="modal-label">Contact method</label><div class="contact-toggle"><button type="button" class="active">Phone</button><button type="button">Instagram</button></div><input class="modal-input" placeholder="Enter 8-digit phone number" /><button class="button primary accept-mission" type="button" data-complete-registration>Confirm registration</button></div>`;
  $("#activityModal").classList.remove("hidden");
  document.body.classList.add("modal-open");
}
$("#activityGrid").addEventListener("click", event => { const button = event.target.closest("[data-register]"); if (!button) return; const activity = activities.find(item => item.id === Number(button.dataset.register)); openActivityBrief(activity); });
$("#activityModal").addEventListener("click", event => { if (event.target.matches("[data-close-activity]")) closeActivityModal(); const accept = event.target.closest("[data-accept-activity]"); if (accept) openRegistration(activities.find(item => item.id === Number(accept.dataset.acceptActivity))); const pax = event.target.closest("[data-pax]"); if (pax) { const value = Math.max(1, Math.min(8, Number($("#modalPax").textContent) + Number(pax.dataset.pax))); $("#modalPax").textContent = value; } const time = event.target.closest(".modal-times button"); if (time) { $$(".modal-times button").forEach(button => button.classList.remove("active")); time.classList.add("active"); } const contact = event.target.closest(".contact-toggle button"); if (contact) { $$(".contact-toggle button").forEach(button => button.classList.remove("active")); contact.classList.add("active"); } if (event.target.closest("[data-complete-registration]")) { closeActivityModal(); toast("Registration request saved. Our team will follow up with the next steps."); } });
document.addEventListener("keydown", event => { if (event.key === "Escape" && !$("#activityModal").classList.contains("hidden")) closeActivityModal(); });
$("#customForm").addEventListener("submit", event => { event.preventDefault(); event.currentTarget.reset(); $("#customStatus").textContent = "Request received. A coordinator will review the details and reply with possible next steps."; toast("Tailored activity request sent"); });
$("#showIdeaForm").addEventListener("click", () => $("#ideaForm").classList.toggle("hidden"));
$("#ideaForm").addEventListener("submit", event => { event.preventDefault(); const form = new FormData(event.currentTarget); ideas.unshift({ title: form.get("title"), description: form.get("description"), votes: 0 }); localStorage.setItem("cb_ideas", JSON.stringify(ideas)); event.currentTarget.reset(); event.currentTarget.classList.add("hidden"); renderIdeas(); toast("Your idea is now on the community board"); });
$("#ideaList").addEventListener("click", event => { const button = event.target.closest("[data-vote]"); if (!button) return; const index = Number(button.dataset.vote); if (votes[index]) return toast("You have already voted for this idea"); ideas[index].votes++; votes[index] = true; localStorage.setItem("cb_votes", JSON.stringify(votes)); localStorage.setItem("cb_ideas", JSON.stringify(ideas)); renderIdeas(); });
$$('[data-scroll]').forEach(button => button.addEventListener("click", () => go(button.dataset.scroll)));
$$('[data-survey]').forEach(button => button.addEventListener("click", () => toast(`${button.dataset.survey} check-in placeholder opened.`)));
$('[data-reflection]').addEventListener("click", () => toast("Reflection prompts are ready for your next activity."));
$$('[data-resource]').forEach(button => button.addEventListener("click", () => toast(`${button.dataset.resource} download placeholder selected.`)));
$("#chatLauncher").addEventListener("click", () => { $("#chatWidget").classList.add("open"); $("#chatWidget").setAttribute("aria-hidden", "false"); $("#chatInput").focus(); });
$("#chatClose").addEventListener("click", () => { $("#chatWidget").classList.remove("open"); $("#chatWidget").setAttribute("aria-hidden", "true"); });
$("#chatForm").addEventListener("submit", event => { event.preventDefault(); const input = $("#chatInput"); const question = input.value.trim(); if (!question) return; chatMessage(question, "user"); input.value = ""; setTimeout(() => chatMessage(answer(question)), 250); });
$$('[data-chat]').forEach(button => button.addEventListener("click", () => { chatMessage(button.dataset.chat, "user"); setTimeout(() => chatMessage(answer(button.dataset.chat)), 250); }));
$$('[data-lang]').forEach(button => button.addEventListener("click", () => { $$('[data-lang]').forEach(item => item.classList.remove("active")); button.classList.add("active"); toast(`${button.textContent} selected. More translated content is coming soon.`); }));
renderActivities(); renderIdeas();
function selectAgent(agentId, notify = true) {
  localStorage.setItem("cb_agent", agentId);
  $$("[data-agent]").forEach(card => card.classList.toggle("selected", card.dataset.agent === agentId));
  $$('[data-select-agent]').forEach(button => {
    const selected = button.dataset.selectAgent === agentId;
    button.classList.toggle("selected", selected);
    button.textContent = selected ? "Selected" : "Select this agent";
  });
  if (notify) toast("Agent profile selected");
}
$$('[data-select-agent]').forEach(button => button.addEventListener("click", () => selectAgent(button.dataset.selectAgent)));
